site_name: Isaac Pascoe
site_url: https://impascoe.github.io/

repo_name: impascoe
repo_url: https://github.com/impascoe/

theme:
  favicon: images/favicon.png
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep-purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    logo: fontawesome/solid/microchip
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-X5KFVDGFG2

copyright: >
  Copyright &copy; 2025 Isaac Pascoe –
  <a href="#__consent">Change cookie settings</a>
